title: AI Studio
email: jcapellman@sparkcognition.com
description: AI Studio Documentation Page
baseurl: "/aistudio-docs" 
url: "https://sparkcognition.github.io"
twitter_username: sparkcognition
github_username:  jcapellman

# Build settings
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

footer_content: "Copyright &copy; 2024 All Rights Reserved By SparkCognition"
